// Give a worker a way in, without giving them an email or a password.
//
// The owner taps "Send sign-in link" next to somebody on the Team screen. This
// route asks Supabase for a one-time sign-in link for that person and hands the
// URL back to the owner, who shares it over WhatsApp. The worker taps it on
// their phone, chooses a 4-digit PIN, and never sees an email address or a
// password at any point.
//
// The internal identifier (field-3@otto.local) exists only because Supabase
// Auth needs something to key an account on. Nothing is ever sent to it — the
// domain is not real, and no mail is configured. The owner is the delivery
// mechanism.
//
// WHAT THIS ROUTE MUST NEVER DO, because the last sign-in route written here
// did all three: take the caller's identity from the request body, sign its own
// token, or return a credential to somebody who has not proved who they are.
// The link is generated by Supabase, and only an authenticated owner can ask
// for one — for anybody else this route is indistinguishable from switched off.

import { requireCaller } from './_lib/serverAuth.js';



/** Identifier for a person. Derived from their app id, so it is stable across
 *  renames and cannot collide. `.local` is reserved and never routes mail. */
export function internalEmail(userId) {
  return `${String(userId).toLowerCase().replace(/[^a-z0-9-]/g, '')}@otto.local`;
}

// Read at request time, not import time: a serverless function can be loaded
// before its environment is attached.
const admin = (path, init) => fetch(`${process.env.SUPABASE_URL}${path}`, {
  ...init,
  headers: {
    apikey: process.env.SUPABASE_SERVICE_ROLE_KEY,
    Authorization: `Bearer ${process.env.SUPABASE_SERVICE_ROLE_KEY}`,
    'Content-Type': 'application/json',
  },
});

async function readBody(req) {
  if (req.body && typeof req.body === 'object') return req.body;
  let raw = '';
  for await (const chunk of req) raw += chunk;
  try { return JSON.parse(raw || '{}'); } catch { return {}; }
}

export default async function handler(req, res) {
  // Only an owner hands out access.
  const caller = await requireCaller(req, res, ['owner']);
  if (!caller) return;

  if (req.method !== 'POST') { res.status(405).json({ error: 'method_not_allowed' }); return; }
  if (!process.env.SUPABASE_URL || !process.env.SUPABASE_SERVICE_ROLE_KEY) { res.status(503).json({ error: 'no_server_key' }); return; }

  const { userId, redirectTo } = await readBody(req);
  if (!userId || typeof userId !== 'string') { res.status(400).json({ error: 'missing_user' }); return; }

  try {
    // The person must already exist in our own users table. This route grants
    // access to an existing member of staff; it does not create staff.
    // Every table here is `id` + a `data` jsonb blob, so name and role live
    // inside `data` rather than in columns.
    const lookup = await admin(`/rest/v1/users?id=eq.${encodeURIComponent(userId)}&select=id,data&limit=1`);
    const rows = lookup.ok ? await lookup.json() : [];
    const row = Array.isArray(rows) ? rows[0] : null;
    const person = row && row.data ? { id: row.id, ...row.data } : null;
    if (!person || person.deleted) { res.status(404).json({ error: 'no_such_user' }); return; }

    const email = internalEmail(person.id);

    // Create the Supabase account on first invite; ignore "already registered".
    const created = await admin('/auth/v1/admin/users', {
      method: 'POST',
      body: JSON.stringify({ email, email_confirm: true }),
    });
    let authUid = null;
    if (created.ok) {
      authUid = (await created.json()).id || null;
    } else {
      // Already there — find them so we can store the link to our row.
      const found = await admin(`/auth/v1/admin/users?filter=${encodeURIComponent(email)}`);
      if (found.ok) {
        const body = await found.json();
        const list = body.users || body || [];
        const hit = Array.isArray(list) ? list.find((u) => u.email === email) : null;
        authUid = hit ? hit.id : null;
      }
    }

    // Tie the Supabase account to our user row. This is what getCaller() reads
    // the role from, and it is the only place the two systems are joined.
    if (authUid) {
      await admin(`/rest/v1/users?id=eq.${encodeURIComponent(person.id)}`, {
        method: 'PATCH',
        body: JSON.stringify({ auth_uid: authUid }),
      });
    }

    // Supabase generates the link. We do not construct or sign anything.
    const linkRes = await admin('/auth/v1/admin/generate_link', {
      method: 'POST',
      body: JSON.stringify({
        type: 'magiclink',
        email,
        options: redirectTo ? { redirect_to: redirectTo } : undefined,
      }),
    });
    if (!linkRes.ok) {
      res.status(502).json({ error: 'link_failed' });
      return;
    }
    const link = await linkRes.json();
    const url = link.action_link || (link.properties && link.properties.action_link);
    if (!url) { res.status(502).json({ error: 'link_failed' }); return; }

    res.status(200).json({ ok: true, name: person.name, url });
  } catch (e) {
    res.status(500).json({ error: 'invite_failed', detail: String((e && e.message) || e).slice(0, 200) });
  }
}
