import { chromium as playwrightChromium } from 'playwright';

const PROD='https://otto-kohl.vercel.app';
const SB=process.env.SUPABASE_URL;
const SERVICE=process.env.SUPABASE_SERVICE_ROLE_KEY;
const OWNER='ejnrcgplm@proton.me';
const W1='ejnrcg@yahoo.com';
const W2='emiliojnovo@gmail.com';
const CUSTOMER='QA CUSTOMER 2026-08-14 E2E';
const JOB='QA JOB 2026-08-14 E2E';
const DELETE='QA DELETE TEST 2026-08-14';
const EST='QA ESTIMATE 2026-08-14 E2E';
const INV='QA INVOICE 2026-08-14 E2E';
const WORKER_NOTE='QA WORKER NOTE 2026-08-14 — Trabajador 1 field QA.';
const OWNER_NOTE='QA OWNER NOTE 2026-08-14 — owner workflow note persistence test.';
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const H=()=>({apikey:SERVICE,Authorization:`Bearer ${SERVICE}`,'Content-Type':'application/json'});
async function magic(email){const r=await fetch(`${SB}/auth/v1/admin/generate_link`,{method:'POST',headers:H(),body:JSON.stringify({type:'magiclink',email})});const t=await r.text();let j={};try{j=JSON.parse(t)}catch{}if(!r.ok)throw new Error(`generate_link ${email} ${r.status}: ${t.slice(0,500)}`);return j.action_link||j.properties?.action_link;}
async function authUser(email){const r=await fetch(`${SB}/auth/v1/admin/users?page=1&per_page=1000`,{headers:H()});const j=await r.json();return (j.users||[]).find(u=>(u.email||'').toLowerCase()===email.toLowerCase())||null;}
async function rest(table,q){const r=await fetch(`${SB}/rest/v1/${table}?${q}`,{headers:H()});const t=await r.text();let data=[];try{data=JSON.parse(t)}catch{}return {status:r.status,data,raw:t};}
async function launch(){const chromium=(await import('@sparticuz/chromium')).default;return playwrightChromium.launch({args:chromium.args,executablePath:await chromium.executablePath(),headless:true});}
async function login(page,email){await page.goto(await magic(email),{waitUntil:'domcontentloaded',timeout:30000});await sleep(1200);if(!page.url().startsWith(PROD))await page.goto(PROD,{waitUntil:'domcontentloaded',timeout:30000});await sleep(1300);return page.evaluate(()=>({id:localStorage.getItem('otto_session'),body:document.body.innerText.slice(0,1200)}));}
async function recs(page){return page.evaluate(({CUSTOMER,JOB,W1,W2})=>{const d=window.__db();return {c:d.customers.find(x=>x.name===CUSTOMER),j:d.jobs.find(x=>x.title===JOB),w1:d.users.find(x=>(x.email||'').toLowerCase()===W1),w2:d.users.find(x=>(x.email||'').toLowerCase()===W2)}},{CUSTOMER,JOB,W1,W2});}
async function policyAndConsent(page,allow=true){const o={policy:false,consent:false};if(await page.locator('#policy-scroll').count()){o.policy=true;await page.locator('#policy-scroll').evaluate(el=>{el.scrollTop=el.scrollHeight;el.dispatchEvent(new Event('scroll',{bubbles:true}))});await sleep(150);const box=await page.locator('#policy-signature').boundingBox();if(box){await page.mouse.move(box.x+30,box.y+30);await page.mouse.down();await page.mouse.move(box.x+90,box.y+45,{steps:8});await page.mouse.move(box.x+160,box.y+25,{steps:8});await page.mouse.up();}await sleep(100);if(await page.locator('#policy-confirm:not([disabled])').count())await page.locator('#policy-confirm').check();if(await page.locator('#policy-acknowledge:not([disabled])').count()){await page.locator('#policy-acknowledge').click();await sleep(900);}else{o.policyBlocked=true;return o;}}
const allowBtn=page.getByRole('button',{name:/Allow location|Permitir ubicación/i}).first();const denyBtn=page.getByRole('button',{name:/Continue without location|Continuar sin ubicación/i}).first();if(await allowBtn.count()||await denyBtn.count()){o.consent=true;if(allow&&await allowBtn.count())await allowBtn.click();else if(await denyBtn.count())await denyBtn.click();await sleep(1000);}return o;}
function tinyPng(){return Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAIAAAACCAIAAAD91JpzAAAAFElEQVR42mP8z8DAwMDAxMDAwAAACQAB/2GZzwAAAABJRU5ErkJggg==','base64');}
function dxf(){return Buffer.from('0\nSECTION\n2\nENTITIES\n0\nTEXT\n8\nPLUMBING\n10\n10\n20\n10\n40\n2.5\n1\nQA TEST PLUMBING PLAN - TOILET SINK SHOWER 120 LF COLD 80 LF HOT\n0\nLINE\n8\nCOLD_WATER\n10\n0\n20\n0\n11\n120\n21\n0\n0\nENDSEC\n0\nEOF\n');}
async function pdf(){const m=await import('jspdf');const jsPDF=m.jsPDF||m.default?.jsPDF||m.default;const d=new jsPDF({unit:'pt',format:'letter'});d.setFontSize(18);d.text('QA TEST PLUMBING PLAN 2026-08-14',50,60);d.setFontSize(12);d.text('2 toilets; 3 sinks; 1 shower; 1 water heater',50,100);d.text('Cold water: 120 LF; Hot water: 80 LF; Drain/waste: 100 LF',50,125);d.text('QA ONLY - NOT A REAL CUSTOMER PLAN',50,160);return Buffer.from(d.output('arraybuffer'));}
async function phaseContinue(browser){const page=await browser.newPage({viewport:{width:1440,height:900}});page.on('dialog',d=>d.accept());const out={};out.login=await login(page,OWNER);let {c,j,w1,w2}=await recs(page);if(!c||!j||!w1||!w2)throw new Error('required QA setup records missing');
if(!await authUser(W2)){await page.evaluate(()=>nav('team'));await sleep(150);await page.evaluate(id=>openUserForm(id),w2.id);await sleep(100);await page.evaluate(async id=>await saveUser(id),w2.id);await sleep(2500);}out.workerAuth={w1:!!await authUser(W1),w2:!!await authUser(W2)};
await page.evaluate(id=>openJobForm(id),j.id);await page.locator('#j-desc').fill('QA TEST DATA ONLY — EDITED JOB DESCRIPTION PERSISTED');await page.locator('#j-status').selectOption('onHold');await page.evaluate(id=>saveJob(id),j.id);await sleep(850);await page.evaluate(id=>openJobForm(id),j.id);out.jobEditOnHold=(await page.locator('#j-desc').inputValue()).includes('EDITED JOB DESCRIPTION')&&(await page.locator('#j-status').inputValue())==='onHold';await page.locator('#j-status').selectOption('scheduled');await page.evaluate(id=>saveJob(id),j.id);await sleep(700);
const hasOwnerNote=await page.evaluate(({id,note})=>window.__db().notes.some(n=>n.jobId===id&&n.text===note),{id:j.id,note:OWNER_NOTE});if(!hasOwnerNote){await page.evaluate(id=>openNoteForm(id),j.id);await page.locator('#note-text').fill(OWNER_NOTE);await page.evaluate(id=>saveNote(id),j.id);await sleep(700);}out.ownerNotePersisted=await page.evaluate(({id,note})=>window.__db().notes.some(n=>n.jobId===id&&n.text===note),{id:j.id,note:OWNER_NOTE});
let del=await page.evaluate(n=>window.__db().customers.find(c=>c.name===n),DELETE);if(!del){await page.evaluate(()=>nav('customers'));await page.evaluate(()=>openCustomerForm());await page.locator('#c-name').fill(DELETE);await page.locator('#c-notes').fill('DEDICATED QA DELETION TEST ONLY');await page.evaluate(()=>saveCustomer(''));await sleep(750);del=await page.evaluate(n=>window.__db().customers.find(c=>c.name===n),DELETE);}out.deleteId=del?.id||null;if(del){await page.evaluate(id=>nav('customer',id),del.id);await sleep(150);await page.getByRole('button',{name:/^Delete$|^Eliminar$/i}).first().click();await sleep(1100);}await page.reload({waitUntil:'domcontentloaded'});await sleep(900);await page.evaluate(()=>nav('customers'));out.deleteAbsentUI=!(await page.locator('body').innerText()).includes(DELETE);const dr=del?await rest('customers',`id=eq.${encodeURIComponent(del.id)}&select=id,data`):{status:0,data:[]};out.deleteDb={status:dr.status,row:dr.data?.[0]||null,physical:dr.status===200&&Array.isArray(dr.data)&&dr.data.length===0};
await page.evaluate(()=>nav('home'));await page.getByRole('button',{name:'ES'}).first().click();await sleep(180);out.spanish=/Hoy|Trabajos de hoy|Clientes/i.test(await page.locator('body').innerText());await page.getByRole('button',{name:'EN'}).first().click();await sleep(180);out.english=/Today|Today's jobs|Customers/i.test(await page.locator('body').innerText());await page.reload({waitUntil:'domcontentloaded'});await sleep(650);out.languagePersisted=/Today|Today's jobs|Customers/i.test(await page.locator('body').innerText());out.dashboard=(await page.locator('body').innerText()).slice(0,800);return out;}
async function phaseField(browser){const out={};if(!await authUser(W1))throw new Error('Trabajador 1 has no Supabase auth identity');const ctx=await browser.newContext({viewport:{width:390,height:844},geolocation:{latitude:25.7617,longitude:-80.1918},permissions:['geolocation']});const page=await ctx.newPage();page.on('dialog',d=>d.accept());out.login1=await login(page,W1);out.gates1=await policyAndConsent(page,true);await sleep(500);let {c,j,w1,w2}=await recs(page);out.session1=await page.evaluate(()=>localStorage.getItem('otto_session'));await page.evaluate(()=>nav('jobs'));await sleep(200);const jobsBody=await page.locator('body').innerText();out.worker1SeesAssigned=jobsBody.includes(JOB);await page.evaluate(id=>nav('job',id),j.id);await sleep(250);const jobBody=await page.locator('body').innerText();out.worker1JobInfo=jobBody.includes(JOB)&&jobBody.includes(CUSTOMER);
let live=await page.evaluate(id=>window.__db().jobs.find(j=>j.id===id),j.id);if(!live.activeCheckIn){const b=page.getByRole('button',{name:/Start Job|Comenzar Trabajo/i}).first();if(await b.count())await b.click();else await page.evaluate(id=>startCheckInFlow(id),j.id);await sleep(100);const ack=page.getByRole('button',{name:/Acknowledge|Reconocer/i}).first();if(await ack.count())await ack.click();else await page.evaluate(id=>doCheckIn(id),j.id);await sleep(1200);}out.checkIn=await page.evaluate(({jid,uid})=>({job:window.__db().jobs.find(j=>j.id===jid),events:window.__db().job_events.filter(e=>e.jobId===jid&&e.userId===uid&&e.type==='check_in'),locations:window.__db().locations.filter(l=>l.jobId===jid&&l.userId===uid)}),{jid:j.id,uid:w1.id});
if(!await page.evaluate(({jid,note})=>window.__db().notes.some(n=>n.jobId===jid&&n.text===note),{jid:j.id,note:WORKER_NOTE})){await page.evaluate(id=>openNoteForm(id),j.id);await page.locator('#note-text').fill(WORKER_NOTE);await page.evaluate(id=>saveNote(id),j.id);await sleep(650);}out.workerNote=await page.evaluate(({jid,note})=>window.__db().notes.some(n=>n.jobId===jid&&n.text===note),{jid:j.id,note:WORKER_NOTE});
const hasPhoto=await page.evaluate(id=>window.__db().photos.some(p=>p.jobId===id&&String(p.caption||'').includes('QA')),j.id);if(!hasPhoto){const chooserP=page.waitForEvent('filechooser');await page.evaluate(id=>quickPhoto(id),j.id);const chooser=await chooserP;await chooser.setFiles({name:'QA JOB PHOTO 2026-08-14.png',mimeType:'image/png',buffer:tinyPng()});await sleep(1400);}let photos=await page.evaluate(id=>window.__db().photos.filter(p=>p.jobId===id),j.id);out.photoCount=photos.length;
await page.evaluate(id=>shareLocation(id),j.id);await sleep(1100);out.locationCount=await page.evaluate(({jid,uid})=>window.__db().locations.filter(l=>l.jobId===jid&&l.userId===uid).length,{jid:j.id,uid:w1.id});
await page.evaluate(id=>{const cl=window.__db().job_checklists.find(c=>c.jobId===id);if(cl)cl.items.filter(i=>!i.done).forEach(i=>toggleChecklistItem(id,i.key));else {['arrival','water','noleak','clean','photos'].forEach(k=>toggleChecklistItem(id,k));}},j.id);await sleep(350);await page.evaluate(id=>startCheckOutFlow(id),j.id);await sleep(100);if(await page.locator('#overlay').count())await page.evaluate(id=>doCheckOut(id),j.id);await sleep(1400);out.checkOut=await page.evaluate(({jid,uid})=>({job:window.__db().jobs.find(j=>j.id===jid),events:window.__db().job_events.filter(e=>e.jobId===jid&&e.userId===uid&&e.type==='check_out')}),{jid:j.id,uid:w1.id});await page.evaluate(()=>nav('home'));await page.reload({waitUntil:'domcontentloaded'});await sleep(900);await page.evaluate(id=>nav('job',id),j.id);out.workerPersistence={note:await page.evaluate(({jid,note})=>window.__db().notes.some(n=>n.jobId===jid&&n.text===note),{jid:j.id,note:WORKER_NOTE}),photos:(await page.evaluate(id=>window.__db().photos.filter(p=>p.jobId===id).length,j.id))>0,events:await page.evaluate(id=>window.__db().job_events.filter(e=>e.jobId===id).map(e=>e.type),j.id)};out.mobile={width:await page.evaluate(()=>innerWidth),scrollWidth:await page.evaluate(()=>document.documentElement.scrollWidth),essentialVisible:(await page.locator('body').innerText()).includes(JOB)};await ctx.close();
const owner=await browser.newPage({viewport:{width:1440,height:900}});await login(owner,OWNER);({j,w1}=await recs(owner));await owner.evaluate(id=>nav('job',id),j.id);await sleep(250);const ownerOverview=await owner.locator('body').innerText();await owner.evaluate(id=>nav('job',id,'photos'),j.id);await sleep(200);const ownerPhotoCount=await owner.locator('#jobphotos img').count();await owner.evaluate(()=>nav('map'));await sleep(250);const mapBody=await owner.locator('body').innerText();out.ownerSees={assignment:ownerOverview.includes('Trabajador 1'),workerNote:ownerOverview.includes('QA WORKER NOTE')||await owner.evaluate(({jid,note})=>window.__db().notes.some(n=>n.jobId===jid&&n.text===note),{jid:j.id,note:WORKER_NOTE}),photo:ownerPhotoCount>0,location:mapBody.includes('Trabajador 1')||await owner.evaluate(({jid,uid})=>window.__db().locations.some(l=>l.jobId===jid&&l.userId===uid),{jid:j.id,uid:w1.id}),checkIn:await owner.evaluate(({jid,uid})=>window.__db().job_events.some(e=>e.jobId===jid&&e.userId===uid&&e.type==='check_in'),{jid:j.id,uid:w1.id}),checkOut:await owner.evaluate(({jid,uid})=>window.__db().job_events.some(e=>e.jobId===jid&&e.userId===uid&&e.type==='check_out'),{jid:j.id,uid:w1.id})};
if(await authUser(W2)){const ctx2=await browser.newContext({viewport:{width:390,height:844}});const p2=await ctx2.newPage();out.login2=await login(p2,W2);out.gates2=await policyAndConsent(p2,false);await sleep(450);await p2.evaluate(()=>nav('jobs'));await sleep(200);const b2=await p2.locator('body').innerText();out.worker2NoWrongAssignment=!b2.includes(JOB);out.worker2Session=await p2.evaluate(()=>localStorage.getItem('otto_session'));await ctx2.close();}else out.worker2NoAuth=true;return out;}
async function phaseFinance(browser){const page=await browser.newPage({viewport:{width:1440,height:900}});await login(page,OWNER);const {c,j}=await recs(page);if(!c||!j)throw new Error('QA customer/job missing');let e=await page.evaluate(n=>window.__db().estimates.find(e=>e.title===n),EST);if(!e){await page.evaluate(id=>openEstimateForm(null,id),j.id);await page.locator('#e-title').fill(EST);await page.locator('#e-desc').fill('QA TEST DATA ONLY — estimate persistence and percentage adjustment test.');await page.locator('.el-desc').first().fill('QA Copper pipe');await page.locator('.el-qty').first().fill('10');await page.locator('.el-price').first().fill('12.50');await page.evaluate(()=>addEstimateLine());await page.locator('.el-desc').nth(1).fill('QA Valve');await page.locator('.el-qty').nth(1).fill('2');await page.locator('.el-price').nth(1).fill('25');await page.evaluate(()=>setEstimateAdjustment(.05));await page.evaluate(()=>saveEstimate(''));await sleep(1000);e=await page.evaluate(n=>window.__db().estimates.find(e=>e.title===n),EST);}const out={estimate5:e};out.estimate5Correct=Math.abs((e?.baseSubtotal||0)-175)<.01&&Math.abs((e?.amount||0)-183.75)<.01&&Number(e?.adjustmentPct)===.05;await page.evaluate(()=>nav('home'));await page.reload({waitUntil:'domcontentloaded'});await sleep(850);e=await page.evaluate(n=>window.__db().estimates.find(e=>e.title===n),EST);out.estimate5Persisted=!!e&&Number(e.adjustmentPct)===.05;await page.evaluate(id=>openEstimateForm(id),e.id);await page.evaluate(()=>setEstimateAdjustment(.10));await page.evaluate(id=>saveEstimate(id),e.id);await sleep(850);await page.reload({waitUntil:'domcontentloaded'});await sleep(800);e=await page.evaluate(n=>window.__db().estimates.find(e=>e.title===n),EST);out.estimate10=e;out.estimate10Correct=Math.abs((e?.amount||0)-192.5)<.01&&Number(e?.adjustmentPct)===.10&&e?.jobId===j.id&&e?.customerId===c.id;
let inv=await page.evaluate(n=>window.__db().invoices.find(i=>i.title===n),INV);if(!inv){await page.evaluate(id=>estimateToInvoice(id),e.id);await page.locator('#i-title').fill(INV);await page.locator('#i-amount').fill(String(e.amount));await page.locator('#i-due').fill('2026-09-14');await page.evaluate(()=>saveInvoice(''));await sleep(900);inv=await page.evaluate(n=>window.__db().invoices.find(i=>i.title===n),INV);}out.invoiceCreated=inv;await page.evaluate(()=>nav('home'));await page.reload({waitUntil:'domcontentloaded'});await sleep(800);inv=await page.evaluate(n=>window.__db().invoices.find(i=>i.title===n),INV);out.invoicePersisted=!!inv&&Math.abs(inv.amount-192.5)<.01&&inv.jobId===j.id&&inv.customerId===c.id;await page.evaluate(id=>openInvoiceForm(id),inv.id);await page.locator('#i-due').fill('2026-09-20');await page.evaluate(id=>saveInvoice(id),inv.id);await sleep(650);await page.evaluate(([,iid])=>openPaymentForm(null,iid),[null,inv.id]);await page.locator('#p-amount').fill('50');await page.locator('#p-method').selectOption({label:'Check'});await page.evaluate(()=>savePayment());await sleep(950);await page.reload({waitUntil:'domcontentloaded'});await sleep(750);const fin=await page.evaluate(({est,inv})=>({estimate:window.__db().estimates.find(e=>e.title===est),invoice:window.__db().invoices.find(i=>i.title===inv),payments:window.__db().payments.filter(p=>window.__db().invoices.find(i=>i.title===inv)?.id===p.invoiceId)}),{est:EST,inv:INV});out.final=fin;out.paymentPersisted=fin.payments.some(p=>Number(p.amount)===50&&p.method==='Check')&&Number(fin.invoice?.paid)>=50;return out;}
async function phasePlans(browser){const page=await browser.newPage({viewport:{width:1440,height:900}});await login(page,OWNER);const {j}=await recs(page);if(!j)throw new Error('QA job missing');const out={};const pb=await pdf();await page.evaluate(id=>nav('job',id,'documents'),j.id);await sleep(200);let doc=await page.evaluate(id=>window.__db().documents.find(d=>d.jobId===id&&d.name==='QA PLAN 2026-08-14.pdf'),j.id);if(!doc){const fp=page.waitForEvent('filechooser');await page.evaluate(id=>uploadDoc(id,'doc'),j.id);const fc=await fp;await fc.setFiles({name:'QA PLAN 2026-08-14.pdf',mimeType:'application/pdf',buffer:pb});await sleep(1500);doc=await page.evaluate(id=>window.__db().documents.find(d=>d.jobId===id&&d.name==='QA PLAN 2026-08-14.pdf'),j.id);}out.pdfUploaded=!!doc;out.pdfRecord=doc;if(doc){await page.evaluate(id=>openDoc(id),doc.id);await sleep(350);const b=await page.locator('body').innerText();out.pdfOpens=b.includes('QA PLAN 2026-08-14.pdf');await page.evaluate(()=>closeModal());try{await page.evaluate(id=>analyzeDrawing(id),doc.id);await sleep(9000);const da=await page.evaluate(id=>window.__db().documents.find(d=>d.id===id),doc.id);out.pdfAnalysis={estimate:da?.estimate||null,ocr:da?.ocr||null,body:(await page.locator('body').innerText()).slice(-1800)};}catch(e){out.pdfAnalysisError=String(e).slice(0,800);}}
let plan=await page.evaluate(id=>window.__db().plans.find(p=>p.jobId===id&&p.name==='QA PLAN 2026-08-14.pdf'),j.id);if(!plan){await page.evaluate(id=>nav('job',id,'documents'),j.id);const fp2=page.waitForEvent('filechooser');await page.evaluate(id=>uploadProjectDoc(id,'plan'),j.id);const fc2=await fp2;await fc2.setFiles({name:'QA PLAN 2026-08-14.pdf',mimeType:'application/pdf',buffer:pb});await sleep(1300);plan=await page.evaluate(id=>window.__db().plans.find(p=>p.jobId===id&&p.name==='QA PLAN 2026-08-14.pdf'),j.id);}out.versionedPlan=plan;await page.reload({waitUntil:'domcontentloaded'});await sleep(800);out.planPersists=await page.evaluate(id=>window.__db().plans.some(p=>p.jobId===id&&p.name==='QA PLAN 2026-08-14.pdf'),j.id);
let cad=await page.evaluate(id=>window.__db().documents.find(d=>d.jobId===id&&d.name==='QA PLAN 2026-08-14.dxf'),j.id);if(!cad){await page.evaluate(id=>nav('job',id,'documents'),j.id);const fp3=page.waitForEvent('filechooser');await page.evaluate(id=>uploadDoc(id,'cad'),j.id);const fc3=await fp3;await fc3.setFiles({name:'QA PLAN 2026-08-14.dxf',mimeType:'application/dxf',buffer:dxf()});await sleep(1300);cad=await page.evaluate(id=>window.__db().documents.find(d=>d.jobId===id&&d.name==='QA PLAN 2026-08-14.dxf'),j.id);}out.cadUploaded=!!cad;out.cadRecord=cad;if(cad){await page.evaluate(id=>openDoc(id),cad.id);await sleep(250);out.cadOpens=(await page.locator('body').innerText()).includes('QA PLAN 2026-08-14.dxf');await page.evaluate(()=>closeModal());try{await page.evaluate(id=>analyzeDrawing(id),cad.id);await sleep(9000);const ca=await page.evaluate(id=>window.__db().documents.find(d=>d.id===id),cad.id);out.cadAnalysis={estimate:ca?.estimate||null,ocr:ca?.ocr||null,body:(await page.locator('body').innerText()).slice(-1800)};}catch(e){out.cadAnalysisError=String(e).slice(0,800);}}await page.reload({waitUntil:'domcontentloaded'});await sleep(700);out.attachmentsPersist=await page.evaluate(id=>({pdf:window.__db().documents.some(d=>d.jobId===id&&d.name==='QA PLAN 2026-08-14.pdf'),cad:window.__db().documents.some(d=>d.jobId===id&&d.name==='QA PLAN 2026-08-14.dxf'),plan:window.__db().plans.some(p=>p.jobId===id&&p.name==='QA PLAN 2026-08-14.pdf')}),j.id);return out;}
async function phaseMisc(browser){const page=await browser.newPage({viewport:{width:1440,height:900}});await login(page,OWNER);const out={questions:[]};const qs=[`Who is assigned to ${JOB}?`,`What customer is ${JOB} for?`,`What is the current status of ${JOB}?`];for(const q of qs){await page.evaluate(()=>nav('assistant'));await sleep(150);await page.locator('#chat-in').fill(q);await page.locator('#chat-in').press('Enter');try{await page.waitForSelector('#typing-indicator',{state:'detached',timeout:15000});}catch{}await sleep(250);out.questions.push({q,answer:(await page.locator('#chatlog').innerText()).slice(-1400)});}await page.evaluate(()=>nav('inbox'));await sleep(400);out.inbox={body:(await page.locator('body').innerText()).slice(0,2200),loaded:true};
const screens=['home','customers','jobs','estimates'];out.languages={};for(const s of screens){await page.getByRole('button',{name:'ES'}).first().click();await sleep(120);await page.evaluate(v=>nav(v),s);await sleep(120);const es=(await page.locator('body').innerText()).slice(0,900);await page.getByRole('button',{name:'EN'}).first().click();await sleep(120);await page.evaluate(v=>nav(v),s);await sleep(120);const en=(await page.locator('body').innerText()).slice(0,900);out.languages[s]={es,en};}
await page.evaluate(()=>nav('jobs'));await sleep(150);out.desktop=await page.evaluate(()=>({innerWidth,scrollWidth:document.documentElement.scrollWidth,innerHeight,scrollHeight:document.documentElement.scrollHeight,buttons:Array.from(document.querySelectorAll('button')).filter(b=>{const r=b.getBoundingClientRect();return r.width>0&&r.height>0}).length}));const mctx=await browser.newContext({viewport:{width:390,height:844}});const m=await mctx.newPage();await login(m,OWNER);for(const s of ['home','customers','jobs','estimates']){await m.evaluate(v=>nav(v),s);await sleep(120);out[`mobile_${s}`]=await m.evaluate(()=>({innerWidth,scrollWidth:document.documentElement.scrollWidth,visibleButtons:Array.from(document.querySelectorAll('button')).filter(b=>{const r=b.getBoundingClientRect();return r.width>0&&r.height>0&&r.left<innerWidth&&r.right>0}).length,body:document.body.innerText.slice(0,650)}));}const {j}=await recs(m);await m.evaluate(id=>nav('job',id,'documents'),j.id);await sleep(150);out.mobile_plans=await m.evaluate(()=>({innerWidth,scrollWidth:document.documentElement.scrollWidth,body:document.body.innerText.slice(0,850)}));await mctx.close();return out;}
export default async function handler(req,res){if(req.method!=='GET')return res.status(405).json({ok:false,error:'method_not_allowed'});const phase=String(req.query?.phase||'continue');let browser;try{browser=await launch();let result;if(phase==='continue')result=await phaseContinue(browser);else if(phase==='field')result=await phaseField(browser);else if(phase==='finance')result=await phaseFinance(browser);else if(phase==='plans')result=await phasePlans(browser);else if(phase==='misc')result=await phaseMisc(browser);else throw new Error('unknown phase');return res.status(200).json({ok:true,phase,result});}catch(e){return res.status(500).json({ok:false,phase,error:String(e?.stack||e).slice(0,8000)});}finally{try{if(browser)await browser.close()}catch{}}}
