import { chromium as playwrightChromium } from 'playwright';

const PROD='https://otto-kohl.vercel.app';
const SB=process.env.SUPABASE_URL;
const SERVICE=process.env.SUPABASE_SERVICE_ROLE_KEY;
const OWNER='ejnrcgplm@proton.me';
const RUN='2026-08-14';
const CUSTOMER=`QA CUSTOMER ${RUN} E2E`;
const JOB=`QA JOB ${RUN} E2E`;
const DELETE=`QA DELETE TEST ${RUN}`;
const W1={name:'Trabajador 1',email:'ejnrcg@yahoo.com'};
const W2={name:'Trabajador 2',email:'emiliojnovo@gmail.com'};
const h=()=>({apikey:SERVICE,Authorization:`Bearer ${SERVICE}`,'Content-Type':'application/json'});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function magic(email){const r=await fetch(`${SB}/auth/v1/admin/generate_link`,{method:'POST',headers:h(),body:JSON.stringify({type:'magiclink',email})});const t=await r.text();let j={};try{j=JSON.parse(t)}catch{}if(!r.ok)throw new Error(`magic ${r.status}: ${t}`);return j.action_link||j.properties?.action_link;}
async function rest(table,q=''){const r=await fetch(`${SB}/rest/v1/${table}?${q}`,{headers:h()});const t=await r.text();let j=[];try{j=JSON.parse(t)}catch{}return {status:r.status,data:j,raw:t};}
async function loginOwner(page){const link=await magic(OWNER);await page.goto(link,{waitUntil:'domcontentloaded',timeout:30000});await sleep(1300);if(!page.url().startsWith(PROD))await page.goto(PROD,{waitUntil:'domcontentloaded',timeout:30000});await sleep(1500);const s=await page.evaluate(()=>localStorage.getItem('otto_session'));if(s!=='it-admin-ejn')throw new Error(`owner login failed session=${s} url=${page.url()}`);return s;}
async function addWorker(page,w){await page.evaluate(()=>nav('team'));await sleep(250);await page.getByRole('button',{name:/Add Employee|Agregar empleado/i}).first().click();await page.locator('#u-name').fill(w.name);await page.locator('#u-email').fill(w.email);await page.locator('#u-lang').selectOption('es');await page.locator('#u-status').selectOption('active');await page.locator('#u-notes').fill(`QA TEST ${RUN} — production E2E field-worker account.`);await page.getByRole('button',{name:/^Save$|^Guardar$/i}).last().click();await sleep(2200);return page.evaluate(email=>window.__db().users.find(u=>(u.email||'').toLowerCase()===email.toLowerCase()),w.email);}
async function addCustomer(page,name,notes='QA TEST DATA ONLY'){await page.evaluate(()=>nav('customers'));await sleep(250);let b=page.getByRole('button',{name:/Add Customer|Agregar cliente/i}).first();if(await b.count())await b.click();else await page.evaluate(()=>openCustomerForm());await page.locator('#c-name').fill(name);await page.locator('#c-phone').fill('305-555-0140');await page.locator('#c-email').fill('qa-otto-20260814@example.com');await page.locator('#c-address').fill('100 QA Test Plaza, Miami, FL 33101');await page.locator('#c-notes').fill(notes);await page.getByRole('button',{name:/^Save$|^Guardar$/i}).last().click();await sleep(1600);return page.evaluate(n=>window.__db().customers.find(c=>c.name===n),name);}
export default async function handler(req,res){if(req.method!=='GET')return res.status(405).json({error:'method_not_allowed'});let browser;const out={production:PROD,run:RUN,steps:{},created:{},pin:{requested:'0000',availableInProductionTeamForm:false}};try{const chromium=(await import('@sparticuz/chromium')).default;browser=await playwrightChromium.launch({args:chromium.args,executablePath:await chromium.executablePath(),headless:true});const ctx=await browser.newContext({viewport:{width:1440,height:900}});const page=await ctx.newPage();page.on('dialog',d=>d.accept());await loginOwner(page);out.steps.ownerLogin=true;
const teamInputs=await page.evaluate(()=>{nav('team');return true});await sleep(200);await page.getByRole('button',{name:/Add Employee|Agregar empleado/i}).first().click();out.pin.availableInProductionTeamForm=await page.locator('input[id*=pin i],input[name*=pin i]').count()>0;await page.evaluate(()=>closeModal());
const w1=await addWorker(page,W1);const w2=await addWorker(page,W2);out.created.worker1=w1&&{id:w1.id,name:w1.name,email:w1.email,role:w1.role,active:w1.active};out.created.worker2=w2&&{id:w2.id,name:w2.name,email:w2.email,role:w2.role,active:w2.active};out.steps.workersCreated=!!w1&&!!w2;
const authUsers=await fetch(`${SB}/auth/v1/admin/users?page=1&per_page=1000`,{headers:h()}).then(r=>r.json());const aus=authUsers.users||authUsers;out.steps.workerInvites={w1:(aus||[]).some(u=>(u.email||'').toLowerCase()===W1.email),w2:(aus||[]).some(u=>(u.email||'').toLowerCase()===W2.email)};
let c=await addCustomer(page,CUSTOMER);if(!c)throw new Error('QA customer not created');out.created.customer={id:c.id,name:c.name};await page.evaluate(()=>nav('home'));await sleep(250);await page.reload({waitUntil:'domcontentloaded'});await sleep(1200);await page.evaluate(id=>nav('customer',id),c.id);await sleep(250);out.steps.customerReopen=(await page.locator('body').innerText()).includes(CUSTOMER);
await page.getByRole('button',{name:/^Edit$|^Editar$/i}).first().click();await page.locator('#c-notes').fill('QA TEST DATA ONLY — EDIT PERSISTENCE VERIFIED');await page.locator('#c-address').fill('101 QA Test Plaza, Miami, FL 33101');await page.getByRole('button',{name:/^Save$|^Guardar$/i}).last().click();await sleep(1300);await page.reload({waitUntil:'domcontentloaded'});await sleep(1100);await page.evaluate(id=>nav('customer',id),c.id);await sleep(200);const c2=await page.evaluate(id=>window.__db().customers.find(c=>c.id===id),c.id);out.steps.customerEditPersisted=c2?.notes==='QA TEST DATA ONLY — EDIT PERSISTENCE VERIFIED'&&c2?.address==='101 QA Test Plaza, Miami, FL 33101';
let nb=page.getByRole('button',{name:/New Job|Nuevo trabajo/i}).first();if(await nb.count())await nb.click();else await page.evaluate(id=>openJobForm(null,id),c.id);await page.locator('#j-title').fill(JOB);await page.locator('#j-desc').fill('QA TEST DATA ONLY — plumbing rough-in validation job.');await page.locator('#j-addr').fill('101 QA Test Plaza, Miami, FL 33101');await page.locator('#j-date').fill(RUN);await page.locator('#j-worker').selectOption(w1.id);await page.locator('#j-status').selectOption('scheduled');await page.getByRole('button',{name:/^Save$|^Guardar$/i}).last().click();await sleep(1800);const j=await page.evaluate(n=>window.__db().jobs.find(j=>j.title===n),JOB);if(!j)throw new Error('QA job not created');out.created.job={id:j.id,title:j.title,assignedTo:j.assignedTo,status:j.status};await page.evaluate(()=>nav('home'));await page.reload({waitUntil:'domcontentloaded'});await sleep(1100);await page.evaluate(id=>nav('job',id),j.id);await sleep(250);let jr=await page.evaluate(id=>window.__db().jobs.find(j=>j.id===id),j.id);out.steps.jobReopenPersisted=jr?.assignedTo===w1.id&&jr?.customerId===c.id&&jr?.status==='scheduled';
await page.evaluate(id=>openJobForm(id),j.id);await page.locator('#j-desc').fill('QA TEST DATA ONLY — EDITED JOB DESCRIPTION PERSISTED');await page.locator('#j-status').selectOption('on_hold');await page.getByRole('button',{name:/^Save$|^Guardar$/i}).last().click();await sleep(1000);await page.evaluate(id=>openJobForm(id),j.id);out.steps.jobEditPersisted=(await page.locator('#j-desc').inputValue()).includes('EDITED JOB DESCRIPTION')&&(await page.locator('#j-status').inputValue())==='on_hold';await page.locator('#j-status').selectOption('scheduled');await page.getByRole('button',{name:/^Save$|^Guardar$/i}).last().click();await sleep(900);
await page.evaluate(id=>openNoteForm(id),j.id);await page.locator('#note-text').fill(`QA OWNER NOTE ${RUN} — owner workflow note persistence test.`);await page.getByRole('button',{name:/^Save$|^Guardar$/i}).last().click();await sleep(1000);out.steps.ownerNotePersisted=await page.evaluate(id=>window.__db().notes.some(n=>n.jobId===id&&String(n.text||'').includes('QA OWNER NOTE')),j.id);
const del=await addCustomer(page,DELETE,'DEDICATED QA DELETION TEST ONLY');out.created.deletion={id:del.id,name:del.name};await page.evaluate(id=>nav('customer',id),del.id);await sleep(200);const delBtn=page.getByRole('button',{name:/^Delete$|^Eliminar$/i}).first();await delBtn.click();await sleep(1300);await page.reload({waitUntil:'domcontentloaded'});await sleep(1000);await page.evaluate(()=>nav('customers'));await sleep(200);const uiText=await page.locator('body').innerText();out.steps.deletionAbsentUI=!uiText.includes(DELETE);const row=await rest('customers',`id=eq.${encodeURIComponent(del.id)}&select=id,data,deleted_at`);out.steps.deletionDatabase={status:row.status,row:row.data?.[0]||null,physical:row.status===200&&Array.isArray(row.data)&&row.data.length===0};
await page.evaluate(()=>nav('home'));await sleep(200);await page.getByRole('button',{name:'ES'}).first().click();await sleep(300);const es=await page.locator('body').innerText();out.steps.spanishHome=/Hoy|Trabajos de hoy|Clientes/i.test(es);await page.getByRole('button',{name:'EN'}).first().click();await sleep(250);const en=await page.locator('body').innerText();out.steps.englishHome=/Today|Today's jobs/i.test(en);await page.reload({waitUntil:'domcontentloaded'});await sleep(900);out.steps.languagePersisted=(await page.locator('body').innerText()).includes('Today');
out.finalDb={customer:(await rest('customers',`id=eq.${encodeURIComponent(c.id)}&select=id,data`)).data?.[0]||null,job:(await rest('jobs',`id=eq.${encodeURIComponent(j.id)}&select=id,data`)).data?.[0]||null,workers:(await rest('users',`id=in.(${encodeURIComponent(w1.id)},${encodeURIComponent(w2.id)})&select=id,auth_uid,data`)).data||[]};return res.status(200).json({ok:true,...out});}catch(e){out.error=String(e?.stack||e).slice(0,8000);return res.status(500).json({ok:false,...out});}finally{try{if(browser)await browser.close()}catch{}}}
